node {
   def commit_id
   def repo = 'taliaJB/docker-nodejs-demo'
   def dhub_credentials = 'tdockerhub'
   stage('step pre') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       dir("basics"){
       sh 'npm install --only=dev'
       sh 'npm test'
       }
     }
   }
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v1/', ${"dhub_credentials"}) {
       def app = docker.build("${repo}:${commit_id}", '.').push()
     }
   }
   stage('docker run') {
     sh label: '', script: '''docker rm docker_test
     sh "docker run --rm -tid --name docker_test -p 3000 ${repo}:latest"
     sh 'docker kill docker_test'
      
      '''
     }
   }

